name: Push to another repository

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Git Filter-Repo
        run: |
          pip install git-filter-repo

      # - name: Filter sensitive file
      #   run: |
      #     git filter-repo --path test_private.json --invert-paths

      - name: Create Pull Request
        env:
          PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          # Configure git
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Create a new branch and commit changes
          git checkout -b my-changes
          # Add your changes
          echo "My changes" > my-changes.txt
          git add .
          git commit -m "My changes"

          # Push the branch to the remote repository
          git push -u target my-changes

          # Create a pull request using the GitHub API
          curl \
            -X POST \
            -H "Authorization: token $PUBLIC_REPO_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/vgodsoe/public_repo/pulls \
            -d '{
              "title": "My changes",
              "head": "my-changes",
              "base": "main"
            }'