name: Mirror Repository

on:
  push:
    branches: [ main ]

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Mirror Repository
      env:
        PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
      run: |
        # Configure git
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        # Clone the public repository
        git clone https://github.com/vgodsoe/public_repo.git

        # Navigate into the public repository
        cd public_repo

        # Set the private repository as a remote named 'private'
        git remote add private https://github.com/vgodsoe/private_repo.git

        # Fetch the private repository
        git fetch private

        # Reset the main branch to mirror the private repository
        git reset --hard private/main

        # Push the changes to the public repository
        git push origin main --force